spring.application.name=lensify-backend

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/lensify_db
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# MYSQL DIALECT
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================
server.port=${PORT:8086}

# JWT Configuration
jwt.secret=LensifyOpticalShopManagementSystem2026SecretKeyForJWTAuthentication123456789
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

server.error.include-message=always
server.error.include-stacktrace=always
